services:
  app:
    build: .
    ports:
      - "8080:8080"  # Expose app on port 8080
    environment:
      SPRING_DATA_REDIS_HOST: redis  # Redis service name
      SPRING_DATA_REDIS_PORT: 6379
    depends_on:
      - redis  # Make sure Redis starts first
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      
  redis:
    image: "redis:latest"
    container_name: redis-server
    ports:
      - "6380:6379"  # Expose Redis on port 6379
